name: base
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - r-base=4.0
  - r-dplyr
  - r-ggplot2
  - r-tidyverse
  - r-reshape2
  - r-plotly
  - r-stringr
  - pip
  - pip:
    - matplotlib
    - numpy
    - pandas
    - plotly
    - scikit-learn
  
